INSERT INTO "PRODUCT" VALUES (1, 'Apple','100');
INSERT INTO "PRODUCT" VALUES (2, 'Samsung','70');
INSERT INTO "PRODUCT" VALUES (3, 'Lenovo','30');
INSERT INTO "PRODUCT" VALUES (4, 'Dell','80');
INSERT INTO "PRODUCT" VALUES (5, 'Hp','60');
INSERT INTO "PRODUCT" VALUES (6, 'Acer','50');
INSERT INTO "PRODUCT" VALUES (7, 'LG','90');